### PR TITLE
added basic channel creation using manually entered user in search.jsx

### PR DESCRIPTION
**Pull request by JOHNDRAJ**
Not sure why but for some reason my changes in the backend are not being realized so I tried to update createChannel so that it creates a cxu with the requester and it didn't work.

### CODE REVIEW

**Comment by BrennanAndruss** [comment]
Looks good to me

**Comment by karthik0605** [comment]
> Not sure why but for some reason my changes in the backend are not being realized so I tried to update createChannel so that it creates a cxu with the requester and it didn't work.

Reply: Deployment is linked to main so it won't trigger the build before merging. For testing, use local running.

**Comment by karthik0605** [comment]
Everything else looks good to me

**Comment by Alec-0dell** [comment]
were you able to link the method with the search bar, other than that it looks good to me

**Pull request merged**
