### PR TITLE
Channel frontend

### PR DESCRIPTION
**Pull request by BrennanAndruss**
Added UI elements

- User info and link to profile button
- Message input and send button
- Message components with edit and delete buttons
- Timestamp under messages when clicked

### CODE REVIEW

**Comment by JOHNDRAJ** [comment]
Looks all go to me

**Comment by karthik0605** [comment]
Looks good to me

**Comment by JOHNDRAJ** [comment]
Oops didn't mean to merge. Everyone else should still review

**Comment by Alec-0dell** [comment]
Looks all good. Good work!

**Pull request merged**
